#!/bin/bash

# Mapfolio Frontend Deployment Guide for Cloudflare Pages
# This script provides instructions for deploying to Cloudflare Pages

echo "🌐 Mapfolio Frontend Deployment to Cloudflare Pages"
echo ""
echo "📋 Prerequisites:"
echo "1. GitHub repository with your code"
echo "2. Cloudflare account"
echo "3. Backend API deployed to Render.com"
echo ""
echo "🚀 Deployment Steps:"
echo ""
echo "1. Go to https://dash.cloudflare.com"
echo "2. Navigate to Workers & Pages → Create application"
echo "3. Select Pages → Connect to Git"
echo "4. Select your Mapfolio repository"
echo ""
echo "⚙️  Build Configuration:"
echo "   - Build command: npm run build:prod"
echo "   - Build output directory: dist"
echo "   - Root directory: /"
echo "   - Node.js version: 18"
echo ""
echo "🔑 Environment Variables (add in Cloudflare Pages settings):"
echo "   - VITE_API_URL=https://mapfolio-e4ym.onrender.com"
echo "   - VITE_APP_NAME=Mapfolio"
echo "   - VITE_ENVIRONMENT=production"
echo ""
echo "🎯 After Deployment:"
echo "1. Note your Cloudflare Pages URL"
echo "2. Update backend CORS in Render: Set FRONTEND_URL=your-pages-url"
echo "3. Update AI Services CORS in Render: Set FRONTEND_URL=your-pages-url"
echo ""
echo "📚 For detailed guide, see DEPLOYMENT.md"
echo ""
echo "✨ Features of Cloudflare Pages:"
echo "   - Unlimited bandwidth (free tier)"
echo "   - Global CDN"
echo "   - Automatic HTTPS"
echo "   - Preview deployments"
echo "   - Rollback capability"